version: '3.4'

services:

  postgresql:
    image: postgres:11
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

