server:
  port: 8000

docker:
  host: "${DOCKER_IP:localhost}"

spring:
  main:
    banner-mode: "OFF"
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: "jdbc:postgresql://${docker.host}:5432/postgres?currentSchema=phonecatalog"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      pool-name: jdbc-hiraki-pool
      connection-timeout: 1000
      idle-timeout: 30000
      minimum-idle: 3
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  flyway:
    locations: classpath:db/migration, classpath:db/dataset
    schemas: phonecatalog
    baselineOnMigrate: true

logging:
  level:
    ROOT: INFO
