-- Create TABLE PHONES CATALOG
CREATE TABLE IF NOT EXISTS PHONES_CATALOGUE
(
  PC_ID             UUID UNIQUE             NOT NULL,
  PC_NAME           VARCHAR(50) UNIQUE      NOT NULL,
  PC_PRICE          INT                     NOT NULL,
  PC_IMAGE          VARCHAR(100)            NOT NULL,
  PC_DESCRIPTION    VARCHAR(150)            NOT NULL,

  CONSTRAINT PK_PC_ID PRIMARY KEY (PC_ID)
);

COMMENT ON TABLE PHONES_CATALOGUE IS 'MASMOVIL Phones Catalog';
